# ===========================================================================
# Turns the layouts slangc chose into C++ static_asserts.
#
#   cmake -DSPVASM_DIR=<dir of *.spvasm> -DOUTPUT=<generated .cpp>
#         -P gen_layout_check.cmake
#
# Slang names a pointed-to record `<Name>_natural` in the SPIR-V and decorates
# every member with its byte offset. Pairing those with OpMemberName gives a
# field-by-field comparison against offsetof() on the C++ side, so a record
# that drifts between Core/GPUTypes.ixx and shaders/gpu_types.slang fails the
# build instead of reading garbage on the GPU.
#
# Only records an entry point actually uses appear here; unused ones keep just
# the hand-written size asserts in GPUTypes.ixx.
# ===========================================================================

if(NOT DEFINED SPVASM_DIR OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "gen_layout_check: SPVASM_DIR and OUTPUT are required")
endif()

file(GLOB ASM_FILES "${SPVASM_DIR}/*.spvasm")
if(NOT ASM_FILES)
  message(FATAL_ERROR "gen_layout_check: no .spvasm found in ${SPVASM_DIR}")
endif()

set(STRUCTS "")

foreach(ASM_FILE IN LISTS ASM_FILES)
  file(READ "${ASM_FILE}" ASM)
  string(REPLACE ";" "," ASM "${ASM}")
  string(REPLACE "\r" "" ASM "${ASM}")
  string(REPLACE "\n" ";" ASM_LINES "${ASM}")

  foreach(LINE IN LISTS ASM_LINES)
    # _natural is a record reached through a pointer, _std430 a push block.
    if(LINE MATCHES "OpMemberName %([A-Za-z0-9]+)_(natural|std430) ([0-9]+) \"([A-Za-z0-9_]+)\"")
      set(FIELD_${CMAKE_MATCH_1}_${CMAKE_MATCH_3} "${CMAKE_MATCH_4}")
      list(APPEND STRUCTS "${CMAKE_MATCH_1}")
    elseif(LINE MATCHES "OpMemberDecorate %([A-Za-z0-9]+)_(natural|std430) ([0-9]+) Offset ([0-9]+)")
      set(OFFSET_${CMAKE_MATCH_1}_${CMAKE_MATCH_3} "${CMAKE_MATCH_4}")
    elseif(LINE MATCHES "OpDecorate %_ptr_PhysicalStorageBuffer_([A-Za-z0-9]+)_natural ArrayStride ([0-9]+)")
      set(STRIDE_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
  endforeach()
endforeach()

list(REMOVE_DUPLICATES STRUCTS)
list(SORT STRUCTS)

set(OUT "/* Generated by cmake/gen_layout_check.cmake. Do not edit. */\n")
string(APPEND OUT "#include <cstddef>\n\nimport GPUTypes;\n\n")

foreach(S IN LISTS STRUCTS)
  string(APPEND OUT "/* ${S} */\n")

  if(DEFINED STRIDE_${S})
    string(APPEND OUT
           "static_assert(sizeof(${S}) == ${STRIDE_${S}},\n"
           "              \"${S}: C++ size differs from the shader's\");\n")
  endif()

  foreach(I RANGE 0 31)
    if(NOT DEFINED FIELD_${S}_${I})
      break()
    endif()
    if(DEFINED OFFSET_${S}_${I})
      string(APPEND OUT
             "static_assert(offsetof(${S}, ${FIELD_${S}_${I}}) == ${OFFSET_${S}_${I}},\n"
             "              \"${S}::${FIELD_${S}_${I}} is at a different offset in the shader\");\n")
    endif()
  endforeach()
  string(APPEND OUT "\n")
endforeach()

file(WRITE "${OUTPUT}" "${OUT}")
